<?php

namespace AppBundle\Entity;

/**
 * ActividadConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadConcursoRepository extends \Doctrine\ORM\EntityRepository
{
}
