<?php

namespace AppBundle\Entity;

/**
 * ActividadSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
