<?php

namespace AppBundle\Entity;

/**
 * AhorroSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AhorroSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
