<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioComiteComprasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioComiteComprasRepository extends \Doctrine\ORM\EntityRepository
{
}
