<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoPasantiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoPasantiaRepository extends \Doctrine\ORM\EntityRepository
{
}
