<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioVisitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioVisitasRepository extends \Doctrine\ORM\EntityRepository
{
}
