<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioAhorroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioAhorroRepository extends \Doctrine\ORM\EntityRepository
{
}
