<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioEstructuraOrganizacionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioEstructuraOrganizacionalRepository extends \Doctrine\ORM\EntityRepository
{
}
