<?php

namespace AppBundle\Entity;

/**
 * AsignacionIntegranteConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionIntegranteConcursoRepository extends \Doctrine\ORM\EntityRepository
{
}
