<?php

namespace AppBundle\Entity;

/**
 * AsignacionOrganizacionPasantiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionOrganizacionPasantiaRepository extends \Doctrine\ORM\EntityRepository
{
}
