<?php

namespace AppBundle\Entity;

/**
 * AsignacionMunicipioMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionMunicipioMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
