<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioComiteVamosBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioComiteVamosBienRepository extends \Doctrine\ORM\EntityRepository
{
}
