<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioRutaFinancieraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioRutaFinancieraRepository extends \Doctrine\ORM\EntityRepository
{
}
