<?php

namespace AppBundle\Entity;

/**
 * AsignacionContadorGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionContadorGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
