<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoCLEARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoCLEARRepository extends \Doctrine\ORM\EntityRepository
{
}
