<?php

namespace AppBundle\Entity;

/**
 * AsignacionOrganizacionTerritorioAprendizajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionOrganizacionTerritorioAprendizajeRepository extends \Doctrine\ORM\EntityRepository
{
}
