<?php

namespace AppBundle\Entity;

/**
 * AsignacionBeneficiarioTallerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionBeneficiarioTallerRepository extends \Doctrine\ORM\EntityRepository
{
}
