<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoComiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoComiteRepository extends \Doctrine\ORM\EntityRepository
{
}
