<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoBeneficiarioRutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoBeneficiarioRutaRepository extends \Doctrine\ORM\EntityRepository
{
}