<?php

namespace AppBundle\Entity;

/**
 * AsignacionOrganizacionRutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionOrganizacionRutaRepository extends \Doctrine\ORM\EntityRepository
{
}
