<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoBeneficiarioPasantiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoBeneficiarioPasantiaRepository extends \Doctrine\ORM\EntityRepository
{
}
