<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoRutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoRutaRepository extends \Doctrine\ORM\EntityRepository
{
}
