<?php

namespace AppBundle\Entity;

/**
 * AsignacionGrupoConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGrupoConcursoRepository extends \Doctrine\ORM\EntityRepository
{
}
