<?php

namespace AppBundle\Entity;

/**
 * AsignacionIntegranteComiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionIntegranteComiteRepository extends \Doctrine\ORM\EntityRepository
{
}
