<?php

namespace AppBundle\Entity;

/**
 * AsignacionIntegranteCLEARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionIntegranteCLEARRepository extends \Doctrine\ORM\EntityRepository
{
}
