<?php

namespace AppBundle\Entity;

/**
 * BecaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BecaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
