<?php

namespace AppBundle\Entity;

/**
 * BeneficiarioRutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiarioRutaRepository extends \Doctrine\ORM\EntityRepository
{
}
