<?php

namespace AppBundle\Entity;

/**
 * BeneficiarioAhorroCorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiarioAhorroCorteRepository extends \Doctrine\ORM\EntityRepository
{
}
