<?php

namespace AppBundle\Entity;

/**
 * BeneficiarioPasantiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiarioPasantiaRepository extends \Doctrine\ORM\EntityRepository
{
}
