<?php

namespace AppBundle\Entity;

/**
 * BeneficiarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiarioRepository extends \Doctrine\ORM\EntityRepository
{
}
