<?php

namespace AppBundle\Entity;

/**
 * BeneficiarioSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiarioSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
