<?php

namespace AppBundle\Entity;

/**
 * CalificacionExperienciaExitosaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificacionExperienciaExitosaRepository extends \Doctrine\ORM\EntityRepository
{
}
