<?php

namespace AppBundle\Entity;

/**
 * CapacitacionSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapacitacionSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
