<?php

namespace AppBundle\Entity;

/**
 * ClearSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClearSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
