<?php

namespace AppBundle\Entity;

/**
 * CLEARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLEARRepository extends \Doctrine\ORM\EntityRepository
{
}
