<?php

namespace AppBundle\Entity;

/**
 * ComiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComiteRepository extends \Doctrine\ORM\EntityRepository
{
}
