<?php

namespace AppBundle\Entity;

/**
 * ConcursoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcursoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
