<?php

namespace AppBundle\Entity;

/**
 * ContadorSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContadorSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
