<?php

namespace AppBundle\Entity;

/**
 * ConvocatoriaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvocatoriaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
