<?php

namespace AppBundle\Entity;

/**
 * DocumentoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
