<?php

namespace AppBundle\Entity;

/**
 * EvaluacionFaseSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionFasesSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
