<?php

namespace AppBundle\Entity;

/**
 * EventoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
