<?php

namespace AppBundle\Entity;

/**
 * ExperienciaExitosaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienciaExitosaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
