<?php

namespace AppBundle\Entity;

/**
 * ExperienciaExitosaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienciaExitosaRepository extends \Doctrine\ORM\EntityRepository
{
}
