<?php

namespace AppBundle\Entity;

/**
 * FeriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriaRepository extends \Doctrine\ORM\EntityRepository
{
}
