<?php

namespace AppBundle\Entity;

/**
 * ComiteSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
