<?php

namespace AppBundle\Entity;

/**
 * GrupoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
