<?php

namespace AppBundle\Entity;

/**
 * integrantesCLEARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class integrantesCLEARRepository extends \Doctrine\ORM\EntityRepository
{
}
