<?php

namespace AppBundle\Entity;

/**
 * IntegranteCLEARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegranteCLEARRepository extends \Doctrine\ORM\EntityRepository
{
}
