<?php

namespace AppBundle\Entity;

/**
 * IntegranteSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegranteSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
