<?php

namespace AppBundle\Entity;

/**
 * IntegranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegranteRepository extends \Doctrine\ORM\EntityRepository
{
}
