<?php

namespace AppBundle\Entity;

/**
 * IntegrantesCLEARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrantesCLEARRepository extends \Doctrine\ORM\EntityRepository
{
}
