<?php

namespace AppBundle\Entity;

/**
 * IntegranteJuradosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegranteJuradosRepository extends \Doctrine\ORM\EntityRepository
{
}
