<?php

namespace AppBundle\Entity;

/**
 * IntegranteComiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegranteComiteRepository extends \Doctrine\ORM\EntityRepository
{
}
