<?php

namespace AppBundle\Entity;

/**
 * JuradoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuradoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
