<?php

namespace AppBundle\Entity;

/**
 * JuradosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuradosRepository extends \Doctrine\ORM\EntityRepository
{
}
