<?php

namespace AppBundle\Entity;

/**
 * ListasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListasRepository extends \Doctrine\ORM\EntityRepository
{
}
