<?php

namespace AppBundle\Entity;

/**
 * OrganizacionRutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionRutaRepository extends \Doctrine\ORM\EntityRepository
{
}
