<?php

namespace AppBundle\Entity;

/**
 * OrganizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
