<?php

namespace AppBundle\Entity;

/**
 * OrganizacionTerritorioAprendizajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionTerritorioAprendizajeRepository extends \Doctrine\ORM\EntityRepository
{
}
