<?php

namespace AppBundle\Entity;

/**
 * OrganizacionPasantiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizacionPasantiaRepository extends \Doctrine\ORM\EntityRepository
{
}
