<?php

namespace AppBundle\Entity;

/**
 * PasantiaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasantiaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
