<?php

namespace AppBundle\Entity;

/**
 * PasantiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasantiaRepository extends \Doctrine\ORM\EntityRepository
{
}
