<?php

namespace AppBundle\Entity;

/**
 * POASoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class POASoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
