<?php

namespace AppBundle\Entity;

/**
 * PolizaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolizaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
