<?php

namespace AppBundle\Entity;

/**
 * ProgramaCapacitacionFinancieraSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaCapacitacionFinancieraSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
