<?php

namespace AppBundle\Entity;

/**
 * RutaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
