<?php

namespace AppBundle\Entity;

/**
 * SeguimientoBeneficiarioAhorroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoBeneficiarioAhorroRepository extends \Doctrine\ORM\EntityRepository
{
}
