<?php

namespace AppBundle\Entity;

/**
 * SeguimientoGrupoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoGrupoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
