<?php

namespace AppBundle\Entity;

/**
 * TalentoSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentoSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
