<?php

namespace AppBundle\Entity;

/**
 * TalentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentoRepository extends \Doctrine\ORM\EntityRepository
{
}
