<?php

namespace AppBundle\Entity;

/**
 * TallerSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TallerSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
