<?php

namespace AppBundle\Entity;

/**
 * TerritorioAprendizajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerritorioAprendizajeRepository extends \Doctrine\ORM\EntityRepository
{
}
