<?php

namespace AppBundle\Entity;

/**
 * VisitaSoporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaSoporteRepository extends \Doctrine\ORM\EntityRepository
{
}
